fprintf(1,'Executing %s at %s:\n',mfilename,datestr(now));
ver,
try,
        %% Generated by nipype.interfaces.spm
        if isempty(which('spm')),
             throw(MException('SPMCheck:NotFound', 'SPM not in matlab path'));
        end
        [name, version] = spm('ver');
        fprintf('SPM version: %s Release: %s\n',name, version);
        fprintf('SPM path: %s\n', which('spm'));
        spm('Defaults','fMRI');

        if strcmp(name, 'SPM8') || strcmp(name, 'SPM12b'),
           spm_jobman('initcfg');
           spm_get_defaults('CmdLine', 1);
        end

        jobs{1}.spm.util.defs.fnames = {...
'/Users/eija/Documents/FinnBrain/scripts/fieldmap.nii,1';...
};
jobs{1}.spm.util.defs.comp{1}.id.space = {...
'/Users/eija/Documents/FinnBrain/pipelinedata/FB028043/FB028043_DTI1.nii,1';...
};

        spm_jobman('run', jobs);

        
,catch ME,
fprintf(2,'MATLAB code threw an exception:\n');
fprintf(2,'%s\n',ME.message);
if length(ME.stack) ~= 0, fprintf(2,'File:%s\nName:%s\nLine:%d\n',ME.stack.file,ME.stack.name,ME.stack.line);, end;
end;